tpweb3/Controllers/ProfesorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using tpweb3.Dao;
using tpweb3.Helper;
using tpweb3.Models;
using tpweb3.Servicios;

namespace tpweb3.Controllers
{
    [SessionTimeout]
    [Profesor]
    public class ProfesorController : Controller
    {
            // GET: Profesor
            public ActionResult Inicio()
            {
                    ViewBag.preguntas = PreguntaDao.traerPreguntas();
                    return View();
            }
        [ActionName("acerca-de")]
        public ActionResult acercaDe()
        {
            return View();
        }

        public ActionResult CrearPregunta()
            {
                ViewBag.ultimoNro = PreguntaDao.ObtenerUltimoNumeroPregunta();
                ViewBag.clases = ClaseDao.traerClases();
                ViewBag.temas = TemaDao.traerTemas();
                return View();
            }

            [HttpPost]
            public ActionResult altaPregunta(PreguntaForm param)
            {
            if (ModelState.IsValid)
            {
                if (PreguntaDao.traerPreguntaPorNro(param.nro) != null)
                {
                    TempData["respuesta"] = "Número de pregunta ya existe";
                    return Redirect("/Profesor/error");
                }
                else
                {
                    PreguntaDao.crearPregunta(param);
                    return Redirect("/Profesor/inicio");
                }
            }
            else {
                TempData["respuesta"] = "Hubo errores al crear la pregunta";
                return Redirect("/Profesor/error");
            }
            }

        public ActionResult Modificar(int id)
        {
            if (PreguntaDao.verificarSiPreguntaTieneRespuestas(id))
            {
                ViewBag.hayRespuestas = true;
            }
            else {
                ViewBag.hayRespuestas = null;
            }
            ViewBag.pregunta = PreguntaDao.traerPreguntaPorId(id);
            ViewBag.clases = ClaseDao.traerClases();
            ViewBag.temas = TemaDao.traerTemas();
            return View();
        }

        [HttpPost]
        public ActionResult editarPregunta(int id, PreguntaForm param) {
            if (ModelState.IsValid)
            {
                if (PreguntaDao.editarPregunta(id, param))
                {
                    return Redirect("/Profesor/Inicio");
                }
                else
                {
                    TempData["respuesta"] = "Hubo errores al editar";
                    TempData["class"] = "danger";
                    return Redirect("/Profesor/Inicio");
                }
            }
            else {
                TempData["respuesta"] = "Hubo errores al editar";
                TempData["class"] = "danger";
                return Redirect("/Profesor/Inicio");
            }
        }
        public ActionResult Eliminar(int id)
        {
            if (PreguntaDao.verificarSiPreguntaTieneRespuestas(id))
            {
                TempData["respuesta"] = "No se puede eliminar pregunta con respuestas";
                return Redirect("/profesor/error");
            }
            else
            {
                if (PreguntaDao.eliminarPregunta(id))
                {
                    return Redirect("/Profesor/Inicio");
                }
                else
                {
                    TempData["respuesta"] = "Hubo un error al eliminar la pregunta";
                    return Redirect("/Profesor/error");
                }
            }
        }
        public ActionResult error()
        {
            return View();
        }

        public ActionResult Evaluar(int id, int? filtro)
        {
            ViewBag.respuestas = RespuestaAlumnoServicio.filtrarRespuestas(filtro, id);
            ViewBag.haySinCalificar = RespuestaAlumnoServicio.verificarSiHayRespuestasSinCalificar(id);
            ViewBag.hayMejorRespuesta = RespuestaAlumnoServicio.verificarSiHayMejorRespuesta(id);
            ViewBag.pregunta = PreguntaDao.traerPreguntaPorId(id);
            return View();
        }

        [HttpPost]
        public ActionResult Corregir(int idRespuestaAlumno, int idProfesor, int calificacion) {
            if (!RespuestaAlumnoDao.Corregir(idRespuestaAlumno, idProfesor, calificacion))
            {
                TempData["respuesta"] = "Hubo un error al corregir, intente más tarde.";
                return Redirect("/profesor/error");
            }
            else
            {
                Uri myuri = new Uri(System.Web.HttpContext.Current.Request.Url.AbsoluteUri);
                string pathQuery = myuri.PathAndQuery;
                string hostName = myuri.ToString().Replace(pathQuery, "");
                RespuestaAlumnoServicio.enviarEmailCorregido(idRespuestaAlumno, calificacion, hostName);
                var param = RespuestaAlumnoDao.traerPorId(idRespuestaAlumno);
                return Redirect($"/profesor/evaluar/{param.IdPregunta}");
            }
        }

        public ActionResult marcarMejorRespuesta(int id)
        {
            if (!RespuestaAlumnoDao.marcarMejorRespuesta(id))
            {
                TempData["respuesta"] = "Hubo un error al corregir, intente más tarde.";
                return Redirect("/profesor/error");
            }
            else
            {
                Uri myuri = new Uri(System.Web.HttpContext.Current.Request.Url.AbsoluteUri);
                string pathQuery = myuri.PathAndQuery;
                string hostName = myuri.ToString().Replace(pathQuery, "");
                RespuestaAlumnoServicio.enviarEmailMejorRespuesta(id, hostName);
                var param = RespuestaAlumnoDao.traerPorId(id);
                return Redirect($"/profesor/evaluar/{param.IdPregunta}");
            }
        }
    }
}
 

tpweb3/Views/Profesor/CrearPregunta.cshtml
@{
    Layout = "~/Views/Shared/MenuProfesor.cshtml";
    int ultimoNro = ViewBag.ultimoNro + 1;
}
<form action="/Profesor/altaPregunta" method="POST" id="formularioPregunta">
    <input type="hidden" name="idProfesor" class="col-md-8" value="@HttpContext.Current.Session["id"].ToString()" />
    <div class="form-group">
        <label for="nro" class="col-md-3">Nro</label>
        <input type="number" name="nro" class="col-md-8" value="@ultimoNro" required />
    </div>
    <div class="form-group">
        <label for="clase">Clase</label>
        <select name="clase" class="form-control">
            @foreach (Clase clase in ViewBag.clases)
            {
                <option value="@clase.IdClase">@clase.Nombre</option>
            }
        </select>
    </div>
    <div class="form-group">
        <label>Tema</label>
        <select name="tema" class="form-control">
            @foreach (Tema tema in ViewBag.temas)
            {
                <option value="@tema.IdTema">@tema.Nombre</option>
            }
        </select>
    </div>
    <input type="checkbox" id="checkboxFechas" /> Ingresar fechas
    <div id="fechas" style="display: none;">
        <div class="form-group">
            <label for="disponibleDesde">Disponible Desde</label>
            <input type="datetime-local" name="disponibleDesde" class="form-control" id="disponibleDesde"/>
        </div>
        <div class="form-group">
            <label for="disponibleHasta">Hasta</label>
            <input type="datetime-local" class="form-control" name="disponibleHasta" />
        </div>
        <span id="erroresFecha"></span>
    </div>
    <!-- span class="text-danger" id="errorDisponibleDesde">Ingrese una fecha válida</span>-->
    <div class="form-group">
        <label for="pregunta">Pregunta(*)</label>
        <textarea name="pregunta" class="form-control" required></textarea>
    </div>
    <input type="submit" class="btn btn-info" />
</form>
@section scripts{
    <script>
        $(document).ready(function () {

                    jQuery.validator.addMethod("greaterThan",
        function (value, element, params) {

            if (!/Invalid|NaN/.test(new Date(value))) {
                return new Date(value) > new Date($(params).val());
            }

            return isNaN(value) && isNaN($(params).val())
                || (Number(value) > Number($(params).val()));
        }, 'La fecha de inicio debe ser menor a la fecha de fin');
                })

            $("#formularioPregunta").validate({
                lang: 'es',
                rules: {
                   disponibleHasta: { greaterThan: "#disponibleDesde" }
                }
            });


        $("#checkboxFechas").on("click", function () {
            if ($('#checkboxFechas').prop('checked')) {
                $("#fechas").show("fast");
            } else {
                $("#fechas").hide("fast");
            }
        })

    </script>
}

tpweb3/Views/Profesor/Evaluar.cshtml
@{
    Layout = "~/Views/Shared/MenuProfesor.cshtml";
    ViewBag.Title = "Evaluar";
    Pregunta pregunta = ViewBag.pregunta;
    RespuestaAlumno respuestaAEvaluar = null;
    int i = 0;
}
@section head
{
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />

}

<div class="container-fluid">
    <div>
        <p>@pregunta.Clase.Nombre - @pregunta.Tema.Nombre</p>
        <h1>@pregunta.Nro - @pregunta.Pregunta1</h1> 
        <p>(@pregunta.FechaDisponibleDesde - @pregunta.FechaDisponibleHasta)</p>
        <div class="row">
            <div class="col-lg-12 my-3">
                <div class="pull-right">
                    <div class="btn-group">
                        <a href="@Url.Action("Evaluar", "Profesor")" class="btn btn-default" id="todas">
                            Todas
                        </a>
                        <a href="@Url.Action("Evaluar", "Profesor")?filtro=0" class="btn btn-warning" id="sinCorregir">
                            Sin corregir
                        </a>
                        <a href="@Url.Action("Evaluar", "Profesor")?filtro=1" class="btn btn-success" id="correctas">
                            Correctas
                        </a>
                        <a href="@Url.Action("Evaluar", "Profesor")?filtro=2" class="btn btn-info" id="regular">
                            Regular
                        </a>
                        <a href="@Url.Action("Evaluar","Profesor")?filtro=3" class="btn btn-danger" id="mal">
                            Mal
                        </a>
                    </div>
                </div>
            </div>
        </div>

    <table class="table table-sm" id="tabla">
        <thead>
            <tr>
                <th scope="col" class="text-center"></th>
                <th scope="col" class="text-center"></th>
                <th scope="col" class="text-center"></th>
                <th scope="col" class="text-center"></th>
                @if (!ViewBag.haySinCalificar && !ViewBag.hayMejorRespuesta)
                {
                <th scope="col" class="text-center"></th>
                }
                <th scope="col" class="text-center"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (RespuestaAlumno respuesta in ViewBag.respuestas)
            {
                <tr>
                    <th class="text-center">@respuesta.FechaHoraRespuesta</th>
                    <th class="text-center">@respuesta.Alumno.Nombre  @respuesta.Alumno.Apellido</th>
                    <th class="text-center">@respuesta.Respuesta</th>
                    <th class="text-center">@if (@respuesta.IdResultadoEvaluacion != null)
                    {
                        @respuesta.ResultadoEvaluacion.Resultado
                        }<th>
                    @if (!ViewBag.haySinCalificar && !ViewBag.hayMejorRespuesta) {
                    <th class="text-center"><a href="@Url.Action("MarcarMejorRespuesta","Profesor")/@respuesta.IdRespuestaAlumno" class="btn">Marcar como mejor respuesta</a></th>
                    }
                    @if (respuesta.IdProfesorEvaluador == null && i==0)
                    {
                    <th class="text-center"><a href="#evaluar" rel="modal:open" class="btn">Evaluar</a></th>
                        respuestaAEvaluar = respuesta;
                        i++;
                    }
                </tr>
            }
        </tbody>
    </table>
        <div id="evaluar" class="modal">
           @if(respuestaAEvaluar != null) { 
            <h1>Evaluando respuesta</h1>
            <p>@respuestaAEvaluar.Respuesta</p>
            <form action="@Url.Action("Corregir", "Profesor")" method="POST">
                <input type="hidden" value="@respuestaAEvaluar.IdRespuestaAlumno" name="idRespuestaAlumno"/>
                <input type="hidden" value="@Session["id"]" name="idProfesor"/>
                <div class="btn-group" data-toggle="buttons">
                    <label class="btn btn-success">
                        <input type="radio" value="1" name="calificacion"/>Correcta
                    </label>
                    <label class="btn btn-warning">
                        <input type="radio" value="2" name="calificacion" />Regular
                    </label>
                    <label class="btn btn-danger">
                        <input type="radio" value="3" name="calificacion" />Mal
                    </label>
                </div>
                <input type="submit" class="btn btn-info"/>
            </form>
                <a href="#" rel="modal:close">Cerrar</a>
           }
</div>
</div>
    </div>

@section scripts
{
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
    <script>
    $(document).ready( function () {
        $('#tabla').DataTable({
            "drawCallback": function (settings) {
                $("#tabla thead").remove();
            }
        });
    } );
    </script>
}

tpweb3/Views/Profesor/Inicio.cshtml
@{
    Layout = "~/Views/Shared/MenuProfesor.cshtml";
}
@section head
{
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">

    }

<div class="container-fluid">

        <a href="/Profesor/CrearPregunta" class="btn btn-info">Crear pregunta</a>

        <table class="table table-sm" id="tabla">
            <thead>
                <tr>
                    <th scope="col" class="text-center">Nro</th>
                    <th scope="col" class="text-center">Clase</th>
                    <th scope="col" class="text-center">Tema</th>
                    <th scope="col" class="text-center">Pregunta</th>
                    <th scope="col" class="text-center">Fecha desde</th>
                    <th scope="col" class="text-center">Fecha hasta</th>
                    <th scope="col" class="text-center">Evaluar</th>
                    <th scope="col" class="text-center">Eliminar</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Pregunta pregunta in ViewBag.preguntas)
                {
                    <tr>
                        <th class="text-center">@pregunta.Nro</th>
                        <th class="text-center">@pregunta.Clase.Nombre</th>
                        <th class="text-center">@pregunta.Tema.Nombre</th>
                        <th class="text-center"><a href="/Profesor/Modificar/@pregunta.IdPregunta">@pregunta.Pregunta1</a></th>
                        <th class="text-center">@pregunta.FechaDisponibleDesde</th>
                        <th class="text-center">@pregunta.FechaDisponibleHasta</th>
                        <th class="text-center"><a href="/Profesor/Evaluar/@pregunta.IdPregunta" class="btn">Evaluar</a></th>
                        <th class="text-center"><a href="/Profesor/Eliminar/@pregunta.IdPregunta" class="btn">Eliminar</a></th>
                    </tr>
                }
            </tbody>
        </table>
</div>
@section scripts
{
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <script>
    $(document).ready( function () {
    $('#tabla').DataTable();
    } );
</script>
}

tpweb3/Views/Profesor/Modificar.cshtml
@{
    Layout = "~/Views/Shared/MenuProfesor.cshtml";
    ViewBag.Title = "modificarPregunta";
    Pregunta pregunta = ViewBag.pregunta;
}

@if (ViewBag.hayRespuestas == true)
{
    <p>Ya se recibieron respuestas a esta pregunta, evite hacer modificaciones que puedan repercutir en las respuestas recibidas</p>
}
<form action="/Profesor/editarPregunta" method="POST" id="formularioPregunta">

    <input type="hidden" value="@pregunta.IdPregunta" name="id" />
    <input type="hidden" value="@Session["id"]" name="idProfesor" />
    <div class="form-group">
        <label for="nro" class="col-md-3">Nro</label>
        <input type="number" name="nro" class="col-md-8" value="@pregunta.Nro" required />
    </div>

    <div class="form-group">
        <label for="clase">Clase</label>
        <select name="clase" class="form-control" required id="clase">
            @foreach (Clase clase in ViewBag.clases)
            {
                <option value="@clase.IdClase">@clase.Nombre</option>
            }
        </select>
    </div>
    <div class="form-group">
        <label>Tema</label>
        <select name="tema" class="form-control" required id="tema">
            @foreach (Tema tema in ViewBag.temas)
            {
                <option value="@tema.IdTema">@tema.Nombre</option>
            }
        </select>
    </div>
    <div class="form-group">
        <label for="disponibleDesde">Disponible Desde</label>
        <input type="datetime-local" name="disponibleDesde" class="form-control" id="FechaDisponibleDesde" />
    </div>
    <div class="form-group">
        <label for="disponibleHasta">Hasta</label>
        <input type="datetime-local" class="form-control" name="disponibleHasta" id="FechaDisponibleHasta" />
    </div>
    <div class="form-group">
        <label for="pregunta">Pregunta(*)</label>
        <textarea name="pregunta" class="form-control" required>@pregunta.Pregunta1</textarea>
    </div>
    <div>
        <input type="submit" class="btn btn-danger" />
        <a href="/Profesor/Inicio" class="btn btn-info">Cancelar</a>
    </div>
</form>
@section scripts{
<script>
    $(document).ready(function () {
        $("#clase").val("@pregunta.IdClase");
        $("#tema").val("@pregunta.IdTema");
        @if (pregunta.FechaDisponibleDesde != null)
        {
        <text>  $("#FechaDisponibleDesde").val("@pregunta.FechaDisponibleDesde.Value.ToString("yyyy-MM-ddThh:mm")"); </text>
        }
        @if (pregunta.FechaDisponibleHasta != null) {
        <text>  $("#FechaDisponibleHasta").val("@pregunta.FechaDisponibleHasta.Value.ToString("yyyy-MM-ddThh:mm")"); </text>
        }
    });

    jQuery.validator.addMethod("greaterThan",
function (value, element, params) {

    if (!/Invalid|NaN/.test(new Date(value))) {
        return new Date(value) > new Date($(params).val());
    }

    return isNaN(value) && isNaN($(params).val())
        || (Number(value) > Number($(params).val()));
}, 'La fecha de inicio debe ser menor a la fecha de fin');


    $("#formularioPregunta").validate({
        lang: 'es',
        rules: {
            disponibleHasta: { greaterThan: "#FechaDisponibleDesde" }
        }
    });
</script>
}

tpweb3/Views/Profesor/acerca-de.cshtml
@{
    Layout = "~/Views/Shared/MenuProfesor.cshtml";
}

<h2>Acerca de</h2>
<p>Integrantes: Rocio Milla - Leandro Coronel - Natalia Cipollino</p>